### ISSUE TITLE
Deprecated classes

### ISSUE THREAD

**Issue by MikkoLuhtasaari** [udacity/reactnd-UdaciFitness-complete#10]
7:21:45 AM
▶The StackNavigator function name is deprecated, please use createStackNavigator instead
7:21:46 AM
▶TabNavigator is deprecated. Please use the createBottomTabNavigator or createMaterialTopTabNavigator instead.

**Comment by HasanAlyazidi** [comment]
Just replace
- `StackNavigator` with `createStackNavigator`
- `TabNavigator` with `createBottomTabNavigator` or `createMaterialTopTabNavigator`
