### ISSUE TITLE
Missing imports for Location, Permission and calculateDirection

### ISSUE THREAD

**Issue by Sangsom** [udacity/reactnd-UdaciFitness-complete#9]
https://github.com/udacity/reactnd-UdaciFitness-complete/blob/654fab8ad1502c104a0501adea1819a4f9ab54c1/components/Live.js#L4

import { Foundation } from "@expo/vector-icons";
import { purple, white } from "../utils/colors";
import { Location, Permissions } from "expo";
import { calculateDirection } from "../utils/helpers";

**Comment by hbkwong** [comment]
Resolved last July in https://github.com/udacity/reactnd-UdaciFitness-complete/blob/88ee290877657691d34dbdcfeb8e273b83b1ddcf/components/Live.js
